# Generated by Django 4.2.4 on 2023-09-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(max_length=128, verbose_name='Дата рождения'),
        ),
    ]
