# Generated by Django 4.2.4 on 2023-09-14 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tour_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=256, verbose_name='Имя тура'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='tour_price',
            field=models.CharField(default=django.utils.timezone.now, max_length=256, verbose_name='Цена тура'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(max_length=256, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(max_length=256, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='fullname',
            field=models.CharField(max_length=256, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_data',
            field=models.CharField(max_length=256, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=256, verbose_name='Телефон номер'),
        ),
    ]
